version: '3.7'
services:

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      mssql:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - '80:80'
      - '443:443'


  mssql:
    image: mssql
    container_name: mssql
    build:
      context: .
      dockerfile: Dockerfile_sql
    ports:
      - '1433:1433'  


  web:
    image: web
    container_name: web
    depends_on:
      nginx:
        condition: service_completed_successfully
    build: 
      context: .
      dockerfile: Dockerfile_app


