version: '3.7'
services:

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      web:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - '80:80'
      - '443:443'


  mssql:
    environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=R0tieFAkor.123
    image: mssql
    container_name: mssql
    build:
      context: .
      dockerfile: Dockerfile_sql
    ports:
      - '1433:1433'  


  web:
    image: web
    container_name: web
    depends_on:
      mssql:
        condition: service_started
    build: 
      context: .
      dockerfile: Dockerfile_app
    ports: 
      - "5000:80"


