version: '3.3'
services:
    mssql:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=R0tieFAkor.123
        ports:
            - '1433:1433'
        container_name: sql1
        hostname: sql1
        image: 'mcr.microsoft.com/mssql/server:2022-latest'