version: '3'
services:
  web:
    build: 
      dockerfile: dockerfile.app
    ports:
     - "5000:80"
    volumes:
     - .:/code
  nginx:
    build: 
      dockerfile: dockerfile.nginx
    ports:
      - "9100:80"

