version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile_app
    ports:
     - "5000:80"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - 80:80
      - 443:443
    restart: always

