version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile_app
    ports:
     - "5000:80"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "9100:80"

