version: '3'
services:
  web:
    build: 
      dockerfile: Dockerfile.app
    ports:
     - "5000:80"
    volumes:
  nginx:
    build: 
      dockerfile: Dockerfile.nginx
    ports:
      - "9100:80"

